name: my-first-github-actions
on: [push]
jobs: 
    check-initial:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
            - run: echo "this is first workflow"
    build-app-v1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                 node-version: '14.17.0'
            - name: list out all paths
              run: tree
            - name: list dir
              run: ls
            - name: install node_modules
              run: yarn
            - name: build project
              run: yarn build
            - name: setup finish
              run: echo "finished building"
            
