name: my-first-github-actions
on: [push]
jobs: 
    check-initial:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
            - run: echo "this is first workflow"
    build-app-v1:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - run: tree
            - run: ls
            
